apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
        app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: "arm64v8/vault"
          args:
            - "server"
            - "-dev"
            - "-log-level=debug"
            - "-dev-root-token-id=3e4a5ba1-kube-422b-d1db-844979cab098"
